import { Metadata } from "next";
import { ReactNode, Suspense } from "react";

export const metadata: Metadata = {
  title: "Admin | AmbitFul",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: ReactNode }) {
  return (
    <main className="">
      <Suspense fallback={<div className="p-4 text-sm">Loading...</div>}>
        {children}
      </Suspense>
    </main>
  );
}
