import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Modal } from "@/components/ui/modal";
import { LoginForm } from "@/components/auth/login";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
        <Modal title="Sign in" trigger={null}>
          <LoginForm />
        </Modal>
      </body>
    </html>
  );
}
