import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./query-provider";
import { Providers } from "./theme-provider";
import { Suspense } from "react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AmbitFul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <QueryProvider>
            <Suspense fallback={<div className="p-4">Loading...</div>}>
              {children}
            </Suspense>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
